M48
; DRILL file KiCad 10.0.3 date 2026-10-01T18:46:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-01T18:46:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X145.654Y-46.851
X145.654Y-51.701
T2
X142.624Y-46.551
X142.624Y-52.001
T3
X167.881Y-78.99
X167.881Y-93.98
M30
